### ISSUE TITLE
Zookeeper version 3.5.9 and 3.7.0 no longer supported by the downloads.apache.org

### ISSUE THREAD

**Issue by qiaow02** [aws-quickstart/quickstart-clickhouse-cluster#44]
The Zookeeper version 3.5.9 and 3.7.0 no longer supported by the downloads.apache.org.
Need to upgrade the Zookeeper version from 3.5.9 to 3.5.10 and from 3.7.0 to 3.7.1

https://downloads.apache.org/zookeeper/

**Comment by carlisle-henning** [comment]
This issue was reported 2 months ago and is wasting a lot of time for users trying to launch this "quickstart".

**ISSUE**
The clickhouse-entrypoint-existing-vpc.template.yaml fails and rolls back as it's referencing a Zookeeper version 3.5.9 that does not exist.

To diagnose the failure, the template has to be relaunched without rollback to interrogate the log files.
The Zookeeper version has to be manually corrected from the default and relaunched.

**FIX**
Correct the Default and Allowed Values in your quick start template for the Zookeeper versions.

```
 ZookeeperVersion:
    AllowedValues:
    - '3.5.9'
    - '3.6.3'
    - '3.7.0'
    Default: '3.5.9'
    Description: ZooKeeper version (3.5.9).
    Type: String
```
![zookeeper versions](https://user-images.githubusercontent.com/111024493/184040289-92f435d2-0c4d-495c-bbff-32aaecd7688f.png)
